### ISSUE TITLE
Add to Homebrew for Mac

### ISSUE THREAD

**Issue by usmcfiredog** [MichaelAquilina/zsh-you-should-use#107]
Any chance of adding to Homebrew for Macs?

**Comment by MichaelAquilina** [comment]
Hi @usmcfiredog I'm afraid I will not be taking the time to add any support for homebrew.

This is mainly because I dont use a Mac and do not wish to spend the extra time supporting something I never use (and for that reason never test).

In addition to this, the best way to install and update this plugin is through the use of one of the standard zsh plugin managers.

Feel free to add this plugin to homebrew yourself and then add an entry to the project's README pointing to it if you wish to give it a go.

**Comment by usmcfiredog** [comment]
Thank you since I have your permission I will add it to homebrew. I was exploring that but didn't know how to keep it up to date with your repo for when you make changes.
